---
# tasks file for nginx
  # Needed to install epel-release first
  - name: install nginx and tools
    yum: name={{item}} state=present
    with_items:
    - nginx
    - python-httplib2
    tags: [ 'packages' ]

  - name: deactivate default nginx site
    file: path=/usr/share/nginx/html/index.html state=absent
    notify: restart nginx

  - name: deactivate default nginx config
    file: path=/etc/nginx/nginx.conf state=absent
    notify: restart nginx

  - name: copy nginx main config
    copy: src=nginx.conf dest=/etc/nginx/ mode=0644
    notify: restart nginx

  - name: get active sites
    shell: ls -l /etc/nginx/conf.d
    register: active
    changed_when: "active.stdout_lines != sites.keys()"

  - name: de-activate sites
    file: path=/etc/nginx/conf.d/{{ item }} state=absent
    with_items: "{{ active.stdout_lines }}"
    when: item not in "{{ sites }}"
    notify: restart nginx

  - name: configure nignx site
    template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ item.key }} mode=0644
    with_dict: "{{ sites }}"
    notify: restart nginx

  - name: ensure nginx started
    service: name=nginx state=started enabled=yes
