---
- hosts: database
  become: true
  tasks:
  # In Centos 7 mysql is no longer defaultly available you must use mariadb
  - name: install mariadb
    yum: name=mariadb-server state=present update_cache=yes