---
- hosts: database
  become: true
  tasks:
  # In Centos 7 mysql is no longer defaultly available you must use mariadb
  - name: Install Pre reqs and tools
    yum: name={{item}} state=present update_cache=yes
    with_items:
    - MySQL-python

  - name: install mariadb
    yum: name=mariadb-server state=present update_cache=yes

  - name: ensure Mariadb started
    service: name=mariadb state=started enabled=yes

  - name: add app01 to hosts file for dns recognition
    lineinfile: dest=/etc/hosts line='172.19.85.39 app01'

  - name: add app02 to hosts file for dns recognition
    lineinfile: dest=/etc/hosts line='172.19.85.40 app02'

  - name: add lb01 to hosts file for dns recognition
    lineinfile: dest=/etc/hosts line='172.19.85.38 lb01'

  - name: create demo database.
    mysql_db: name=demo state=present

  - name: create demo user remote
    mysql_user: name=demo password=demo priv=demo.*:ALL,grant host='%' state=present

  - name: create demo user local
    mysql_user: name=demo password=demo priv=demo.*:ALL,grant host='localhost' state=present

  - name: create demo user local ip
    mysql_user: name=demo password=demo priv=demo.*:ALL,grant host='127.0.0.1' state=present

  handlers:
  - name: restart mariadb
    service: name=mariadb state=restarted