---
- hosts: loadbalancer
  become: true
  tasks:
  # Needed to install epel-release first
  - name: install nginx
    yum: name=nginx state=present update_cache=yes

  - name: ensure nginx started
    service: name=nginx state=started enabled=yes