---
# Bring Stack down
- hosts: loadbalncer
  become: true
  tasks:
  - service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
  - service: name=httpd state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
  - service: name=mariadb state=restarted

# Bring stack back up
- hosts: webserver
  become: true
  tasks:
  - service: name=httpd state=started

- hosts: loadbalncer
  become: true
  tasks:
  - service: name=nginx state=started