---
# Are services up and running.
##############################
#
- hosts: loadbalancer
  become: true
  tasks:
  - name: verify nginx service
    command: service nginx status

  - name: verify nginx is listening on 80
    wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
  - name: verify apache service
    command: service httpd status

  - name: verify apache is listening on 80
    wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
  - name: verify mariadb service
    command: service mariadb status

  - name: verify mariadb is listening on 3306
    wait_for: port=3306 timeout=1
