---
# Bring Stack down
- hosts: loadbalncer
  become: true
  tasks:
  - name: stopping loadbalncers
    service: name=nginx state=stopped
    wait_for: port=80 state=drained

- hosts: webserver
  become: true
  tasks:
  - name: stopping webservers
    service: name=httpd state=stopped
    wait_for: port=80 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
  - name: restarting databases
    service: name=mariadb state=restarted
    wait_for: port=3306 state=started

# Bring stack back up
- hosts: webserver
  become: true
  tasks:
  - name: starting webservers
    service: name=httpd state=started
    wait_for: port=80 state=statrted

- hosts: loadbalncer
  become: true
  tasks:
  - name: starting loadbalancer
   service: name=nginx state=started
   wait_for: port=80 state=started