---
# tasks file for mariadb
  # In Centos 7 mysql is no longer defaultly available you must use mariadb
  - name: Install Pre reqs and mariadb
    yum: name={{item}} state=present
    with_items:
    - MySQL-python
    - mariadb-server
    tags: [ 'packages' ]

  - name: ensure mysql listening on all ports
    lineinfile: dest=/etc/my.cnf.d/server.cnf regexp=^bind-address
                line="bind-address={{ansible_default_ipv4.address}}"
    notify: restart mariadb

  - name: ensure Mariadb started
    service: name=mariadb state=started enabled=yes

  - name: create demo database.
    mysql_db: name={{db_name}} state=present

  - name: create dbuser user remote
    mysql_user: name={{db_user_name}} password={{db_user_pass}}
                priv={{db_name}}.*:ALL host='{{db_user_host}}' state=present